// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqtjwhegmpvlvrcstxkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxdGp3aGVnbXB2bHZyY3N0eGtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1NDg1MDcsImV4cCI6MjA1MDEyNDUwN30.9hgpRBhRQTue9Neg_Ta2fu-s0zWpNSI_e0l6H7gCHkE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);